import { Trip, VocabWord } from './types';

export const MOCK_USER = {
  id: '1',
  name: 'Ayşe Yılmaz',
  email: 'ayse@bonvo.ai',
  avatarInitials: 'AY',
};

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip-1',
    destination: 'Tokyo',
    country: 'Japonya',
    flag: '🇯🇵',
    startDate: '2025-07-15',
    endDate: '2025-07-28',
    type: 'culture',
    typeLabelTr: 'Kültür',
    status: 'planned',
    budget: 45000,
    travelers: 2,
    accommodation: 'comfort',
    interests: ['museum', 'street_food', 'temple'],
    progress: 65,
    daysLeft: 28,
  },
  {
    id: 'trip-2',
    destination: 'Roma',
    country: 'İtalya',
    flag: '🇮🇹',
    startDate: '2025-09-03',
    endDate: '2025-09-10',
    type: 'gastronomy',
    typeLabelTr: 'Gastronomi',
    status: 'planned',
    budget: 30000,
    travelers: 2,
    accommodation: 'comfort',
    interests: ['street_food', 'museum', 'art'],
    progress: 20,
    daysLeft: 107,
  },
  {
    id: 'trip-3',
    destination: 'Santorini',
    country: 'Yunanistan',
    flag: '🇬🇷',
    startDate: '2025-01-10',
    endDate: '2025-01-17',
    type: 'beach',
    typeLabelTr: 'Plaj',
    status: 'completed',
    budget: 25000,
    travelers: 2,
    accommodation: 'luxury',
    interests: ['beach', 'photography'],
    progress: 100,
    daysLeft: 0,
  },
];

export const MOCK_VOCAB_WORDS: VocabWord[] = [
  {
    id: 'w1',
    tripId: 'trip-1',
    original: 'Arigatou (ありがとう)',
    translation: 'Teşekkür ederim',
    example: '"Arigatou gozaimasu" — resmi teşekkür',
    status: 'learned',
  },
  {
    id: 'w2',
    tripId: 'trip-1',
    original: 'Sumimasen (すみません)',
    translation: 'Özür dilerim / Affedersiniz',
    example: 'Dikkat çekmek veya özür dilemek için',
    status: 'learning',
  },
  {
    id: 'w3',
    tripId: 'trip-1',
    original: 'Ikigai (生き甲斐)',
    translation: 'Yaşam amacı / Varoluş nedeni',
    example: 'Felsefi kavram, çevirisi zor',
    status: 'hard',
  },
  {
    id: 'w4',
    tripId: 'trip-1',
    original: 'Kawaii (かわいい)',
    translation: 'Sevimli / Tatlı',
    example: 'Japon kültüründe yaygın estetik kavramı',
    status: 'learned',
  },
  {
    id: 'w5',
    tripId: 'trip-1',
    original: 'Itadakimasu (いただきます)',
    translation: 'Afiyet olsun (yemek öncesi)',
    example: 'Yemek başlamadan önce söylenir',
    status: 'learning',
  },
  {
    id: 'w6',
    tripId: 'trip-1',
    original: 'Wabi-sabi (侘寂)',
    translation: 'Kusurlu güzellik felsefesi',
    example: 'Geçicilik ve eksikliğin güzelliği',
    status: 'hard',
  },
  {
    id: 'w7',
    tripId: 'trip-1',
    original: 'Konnichiwa (こんにちは)',
    translation: 'İyi günler / Merhaba',
    example: 'Gündüz kullanılan selamlama',
    status: 'learned',
  },
  {
    id: 'w8',
    tripId: 'trip-1',
    original: 'Sayonara (さようなら)',
    translation: 'Güle güle / Elveda',
    example: 'Resmi vedalaşma ifadesi',
    status: 'learning',
  },
];

export const TRIP_TYPES = [
  { value: 'culture', label: 'Kültür', icon: '🏛️' },
  { value: 'beach', label: 'Plaj', icon: '🏖️' },
  { value: 'gastronomy', label: 'Gastronomi', icon: '🍜' },
  { value: 'nature', label: 'Doğa', icon: '🏔️' },
  { value: 'shopping', label: 'Alışveriş', icon: '🛍️' },
  { value: 'art', label: 'Sanat', icon: '🎨' },
] as const;

export const INTERESTS = [
  { value: 'museum', label: '🖼️ Müze' },
  { value: 'hiking', label: '🌿 Doğa Yürüyüşü' },
  { value: 'street_food', label: '🍣 Sokak Yemeği' },
  { value: 'theater', label: '🎭 Tiyatro' },
  { value: 'photography', label: '📸 Fotoğrafçılık' },
  { value: 'temple', label: '⛩️ Tapınak' },
  { value: 'anime', label: '🎮 Anime & Manga' },
  { value: 'spa', label: '♨️ Termal Spa' },
  { value: 'beach', label: '🏖️ Plaj' },
  { value: 'art', label: '🎨 Sanat Galerisi' },
];
